### ISSUE TITLE
Crash when requesting LeagueData

### ISSUE THREAD

**Issue by Hannes01071995** [p-ob/LolSharp#1]
When requesting LeagueData LoLSharp will crash due to a null reference.

The cause seems to be that RestSharp will return null as Data form the request.
When taking a closer look, you can see that the response (in RiotApiClient.Execute) will have an error exception set.

**Comment by p-ob** [comment]
Interesting. This seems to have risen when I was using IEnumerable instead of List when passing types to RestSharp's Execute<>(). This should be resolved with the most recent commit!
