### ISSUE TITLE
SummonerById?

### ISSUE THREAD

**Issue by Hannes01071995** [p-ob/LolSharp#2]
Hey,

is it possible to get the SummonerById request implemented?
I need it since i have a set of summonerIds and want to update the summoner itself.
Names wont be enough since they might be changed by some summoners.

Would be really helpful.
Thanks!

**Comment by p-ob** [comment]
This should be in the most recent commit! I'll do some more testing on it, but as far as I know it's functional! More or less an oversight; hadn't needed it so I just hadn't added it yet!
